#!/usr/bin/env python3
"""Generate stock-scout-data.js from the latest CSVs, then open the v2 HTML."""

import csv
import json
import subprocess
import sys
from pathlib import Path

from dashboard import load_sectors

OUTPUT_DIR = Path("output")


def csv_to_rows(path: Path):
    """Return (js_rows, mt_data) from a scout/signa/ai_sector CSV.

    js_rows: list of dicts matching the JS row schema.
    mt_data: {ticker: {state, spread}} from mt_state/mt_spread_pct columns.
    """
    js_rows = []
    mt_data = {}
    with open(path, newline="") as f:
        for r in csv.DictReader(f):
            ticker = r["ticker"]
            js_rows.append({
                "ticker":    ticker,
                "rank":      int(r["rank"]),
                "score":     float(r["score"]),
                "r_squared": float(r["r_squared"]),
                "m1": int(r["m1"] == "True"), "m2": int(r["m2"] == "True"),
                "m3": int(r["m3"] == "True"), "m4": int(r["m4"] == "True"),
                "m5": int(r["m5"] == "True"), "m6": int(r["m6"] == "True"),
                "m7": int(r["m7"] == "True"), "m8": int(r["m8"] == "True"),
                "all_pass":  int(r["all_pass"] == "True"),
                "close":     float(r["close"]),
                "sma50":     float(r["sma50"]),
                "sma150":    float(r["sma150"]),
                "sma200":    float(r["sma200"]),
                "dist_52h":  float(r["dist_from_52w_high_pct"]),
                "ret_5d":    float(r["ret_5d"]),
                "dist_10dh": float(r["dist_from_10d_high"]),
                "pullback":  int(r["pullback"] == "True"),
                "day_chg":   float(r.get("day_chg") or 0),
            })
            mt_data[ticker] = {
                "state":  r.get("mt_state") or "BULL",
                "spread": float(r.get("mt_spread_pct") or 0),
            }
    return js_rows, mt_data


def main():
    scout_csvs = sorted(OUTPUT_DIR.glob("scout_*.csv"), reverse=True)
    signa_csvs = sorted(OUTPUT_DIR.glob("signa_*.csv"), reverse=True)
    ai_csvs    = sorted(OUTPUT_DIR.glob("ai_sector_*.csv"), reverse=True)

    if not scout_csvs:
        raise FileNotFoundError("No scout CSV found in output/ — run scout.py first.")

    data,      mt1 = csv_to_rows(scout_csvs[0])
    signa,     mt2 = csv_to_rows(signa_csvs[0]) if signa_csvs else ([], {})
    ai_sector, mt3 = csv_to_rows(ai_csvs[0])    if ai_csvs    else ([], {})

    mt_data    = {**mt1, **mt2, **mt3}
    sector_map = load_sectors()
    scan_date  = scout_csvs[0].stem.replace("scout_", "")

    js = f"""// AUTO-GENERATED by generate_dashboard_v2.py — do not edit by hand
const SCAN_DATE = {json.dumps(scan_date)};
const UNIVERSE = "S&P 500";
const SPY = {{ close: 0, change_pct: 0 }};
const SECTOR_OF = {json.dumps(sector_map, indent=2)};
const SECTOR_COLORS = {{
  "Tech":        "#4da6ff",
  "Healthcare":  "#3ee0a8",
  "Financials":  "#b18bff",
  "Cons. Disc.": "#ff9340",
  "Industrials": "#6680ff",
  "Comm. Svcs":  "#ff6b9c",
  "Energy":      "#f4c860",
  "Staples":     "#7dd6a0",
  "Utilities":   "#88c4ff",
  "Real Estate": "#ff8fbe",
  "Materials":   "#c9a96e"
}};
const DATA      = {json.dumps(data)};
const SIGNA     = {json.dumps(signa)};
const AI_SECTOR = {json.dumps(ai_sector)};
const MT_DATA   = {json.dumps(mt_data)};
"""

    out = OUTPUT_DIR / "stock-scout-data.js"
    out.write_text(js, encoding="utf-8")
    print(
        f"Wrote {out}  "
        f"({len(data)} main + {len(signa)} signa + {len(ai_sector)} AI sector rows)"
    )

    html = OUTPUT_DIR / "Stock Scout v2.html"
    if html.exists():
        if sys.platform == "win32":
            subprocess.Popen(["start", "", str(html.resolve())], shell=True)
        elif sys.platform == "darwin":
            subprocess.Popen(["open", str(html.resolve())])
        elif sys.platform.startswith("linux"):
            subprocess.Popen(["xdg-open", str(html.resolve())])


if __name__ == "__main__":
    main()
